### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by JoeNyland** [JoeNyland/puppet-cloudwatch#1]
```
/Users/joenyland/.rvm/rubies/ruby-2.2.1/bin/ruby -I/Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/rspec-core-3.4.4/lib:/Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/rspec-support-3.4.1/lib /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/rspec-core-3.4.4/exe/rspec --pattern spec/\{classes,defines,unit,functions,hosts,integration,types\}/\*\*/\*_spec.rb --color
F

Failures:

  1) cloudwatch with default values for all parameters should contain Class[cloudwatch]
     Failure/Error: it { should contain_class('cloudwatch') }

     Puppet::PreformattedError:
       Evaluation Error: Error while evaluating a Function Call, Could not find class ::cloudwatch for joes-mbp.home at line 1:1 on node joes-mbp.home
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/parser/compiler.rb:387:in `block in evaluate_classes'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/parser/compiler.rb:386:in `collect'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/parser/compiler.rb:386:in `evaluate_classes'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/parser/functions/include.rb:33:in `block in <top (required)>'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/parser/functions.rb:174:in `block (2 levels) in newfunction'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/util/profiler.rb:51:in `profile'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/parser/functions.rb:167:in `block in newfunction'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/pops/evaluator/runtime3_support.rb:281:in `call_function'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/pops/evaluator/evaluator_impl.rb:912:in `call_function_with_block'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/pops/evaluator/evaluator_impl.rb:881:in `eval_CallNamedFunctionExpression'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/pops/visitor.rb:48:in `block in visit_this'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/pops/visitor.rb:42:in `each'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/pops/visitor.rb:42:in `visit_this'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/pops/visitor.rb:71:in `visit_this_1'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/pops/evaluator/evaluator_impl.rb:77:in `evaluate'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/pops/evaluator/evaluator_impl.rb:691:in `eval_Program'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/pops/visitor.rb:48:in `block in visit_this'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/pops/visitor.rb:42:in `each'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/pops/visitor.rb:42:in `visit_this'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/pops/visitor.rb:71:in `visit_this_1'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/pops/evaluator/evaluator_impl.rb:77:in `evaluate'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/pops/parser/evaluating_parser.rb:63:in `evaluate'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/parser/ast/pops_bridge.rb:119:in `evaluate'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/parser/ast.rb:31:in `safeevaluate'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/resource/type.rb:182:in `evaluate_code'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/parser/resource.rb:84:in `block in evaluate'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/util/profiler.rb:51:in `profile'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/parser/resource.rb:76:in `evaluate'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/parser/compiler.rb:637:in `evaluate_main'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/parser/compiler.rb:179:in `block (2 levels) in compile'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/util/profiler.rb:51:in `profile'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/parser/compiler.rb:179:in `block in compile'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/context.rb:65:in `override'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet.rb:240:in `override'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/parser/compiler.rb:167:in `compile'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/parser/compiler.rb:35:in `compile'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/indirector/catalog/compiler.rb:266:in `block (2 levels) in compile'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/util/profiler.rb:51:in `profile'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/indirector/catalog/compiler.rb:264:in `block in compile'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/util.rb:223:in `block in benchmark'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/util.rb:222:in `benchmark'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/indirector/catalog/compiler.rb:262:in `compile'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/indirector/catalog/compiler.rb:53:in `find'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/indirector/indirection.rb:194:in `find'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/rspec-puppet-2.4.0/lib/rspec-puppet/adapters.rb:74:in `catalog'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/rspec-puppet-2.4.0/lib/rspec-puppet/adapters.rb:148:in `catalog'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/rspec-puppet-2.4.0/lib/rspec-puppet/support.rb:169:in `build_catalog_without_cache'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/rspec-puppet-2.4.0/lib/rspec-puppet/support.rb:178:in `block in build_catalog'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/rspec-puppet-2.4.0/lib/rspec-puppet/cache.rb:17:in `call'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/rspec-puppet-2.4.0/lib/rspec-puppet/cache.rb:17:in `get'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/rspec-puppet-2.4.0/lib/rspec-puppet/support.rb:177:in `build_catalog'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/rspec-puppet-2.4.0/lib/rspec-puppet/support.rb:30:in `load_catalogue'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/rspec-puppet-2.4.0/lib/rspec-puppet/example/class_example_group.rb:7:in `catalogue'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/rspec-puppet-2.4.0/lib/rspec-puppet/support.rb:10:in `block in subject'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/rspec-puppet-2.4.0/lib/rspec-puppet/matchers/create_generic.rb:82:in `call'
     # /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/rspec-puppet-2.4.0/lib/rspec-puppet/matchers/create_generic.rb:82:in `matches?'
     # ./spec/classes/init_spec.rb:4:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Puppet::Error:
     #   Could not find class ::cloudwatch for joes-mbp.home
     #   /Users/joenyland/.rvm/gems/ruby-2.2.1@puppet-cloudwatch/gems/puppet-4.5.1-universal-darwin/lib/puppet/parser/compiler.rb:387:in `block in evaluate_classes'

Finished in 0.1024 seconds (files took 0.65717 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/classes/init_spec.rb:4 # cloudwatch with default values for all parameters should contain Class[cloudwatch]
```

**Comment by JoeNyland** [comment]
This was fixed in #3.
